### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Penrock1547** [littlebits/cloud-api-lessons#2]
Hey i was following this great little tutorial and ran into a problem.  I have the app deployed to heroku but it keeps crashing with the following error written to the logs:

```
**Starting process with command `node ./seed-cloudbit-reader/index.js`
App booted at: {"address":"0.0.0.0","family":"IPv4","port":3615}
State changed from starting to up
SyntaxError: Unexpected end of input
at Object.parse (native)
undefined:0
at IncomingMessage.emit (events.js:92:17)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)
^
at IncomingMessage.<anonymous> (/app/seed-cloudbit-reader/index.js:11:30)
2015-01-04T01:38:52.290746+00:00 app[web.1]: 
Process exited with status 8
State changed from up to crashed
 State changed from crashed to starting
Starting process with command `node ./seed-cloudbit-reader/index.js`**

Not sure if the build process picked up the right version of Node.js because there was a warning in the build log from Heroku as follows.  However the package.json files does specify a version I think.

**-----> Node.js app detected
-----> Resetting git environment

      * PRO TIP: Specify a node version in package.json
       See https://devcenter.heroku.com/articles/nodejs-support*

-----> Defaulting to latest stable node: 0.10.35
-----> Downloading and installing node
-----> Exporting config vars to environment
-----> Installing dependencies
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web

-----> Compressing... done, 5.5MB
-----> Launching... done, v3
```

Any help would be appreciated, thanks!

**Comment by jasonkuhrt** [comment]
Hey @Penrock1547 I checking this now thanks. Seems like there is some invalid JSON coming through.

**Comment by jasonkuhrt** [comment]
Hey @Penrock1547 Just wanted to inform you that we'll have this fixed tomorrow.

**Comment by Penrock1547** [comment]
Cool! 

Thanks Jason.

Joey
